import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {spawn} from 'node:child_process';

const workflow=(status='active')=>({id:'30c43067-cb05-458c-b2b5-5b77099c0f18',name:'Process Customer Request',source:'activity-discovery',status,discoverySignature:'open_email|download_attachment|search_customer|update_customer|send_message',avgDuration:684,actions:[['Gmail','Open customer email'],['Files','Download attachment'],['CRM','Search customer'],['CRM','Update customer record'],['Slack','Send notification']].map(([application,action],order)=>({id:`step-${order}`,application,action,order:order+1}))});
const activity=[{id:'request-1',application:'Gmail',action:'Opened customer request',metadata:{customer:'ABC Technologies',request:'customer request details',attachment:'customer_request.pdf'}}];

async function startFixture(t,{status='active',customers=[{id:'CUST-001',name:'ABC Technologies'}]}={}){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'workflowos-execution-')),store=path.join(dir,'data.json'),port=3200+Math.floor(Math.random()*300);fs.writeFileSync(store,JSON.stringify({users:[{id:'user-1',name:'Test',email:'test@example.com',passwordHash:'x'}],sessions:{testtoken:'user-1'},observing:false,events:activity,workflows:[workflow(status)],executions:[],integrations:[],crmCustomers:customers,slackMessages:[]}));const child=spawn(process.execPath,['server/index.js'],{cwd:process.cwd(),env:{...process.env,PORT:String(port),WORKFLOWOS_DATA_FILE:store},stdio:'ignore'});t.after(()=>{child.kill();fs.rmSync(dir,{recursive:true,force:true})});for(let attempt=0;attempt<20;attempt++){try{await fetch(`http://localhost:${port}/api/workflows`,{headers:{Authorization:'Bearer testtoken'}});break}catch{await new Promise(resolve=>setTimeout(resolve,50))}}return{store,request:(id='30c43067-cb05-458c-b2b5-5b77099c0f18')=>fetch(`http://localhost:${port}/api/workflows/${id}/run`,{method:'POST',headers:{Authorization:'Bearer testtoken'}})}}

test('an active customer-request workflow executes all local steps and persists outcomes',async t=>{const fixture=await startFixture(t);const response=await fixture.request();assert.equal(response.status,200);const execution=await response.json();assert.equal(execution.status,'completed');assert.equal(execution.workflowId,'30c43067-cb05-458c-b2b5-5b77099c0f18');assert.equal(execution.workflowName,'Process Customer Request');assert.equal(execution.humanInterventionRequired,false);assert.deepEqual(execution.steps.map(step=>step.step),['gmail','download_attachment','crm_search','crm_update','slack_notification']);assert.ok(execution.steps.every(step=>step.status==='completed'));const persisted=JSON.parse(fs.readFileSync(fixture.store));assert.equal(persisted.workflows[0].id,'30c43067-cb05-458c-b2b5-5b77099c0f18');assert.equal(persisted.workflows[0].status,'active');assert.equal(persisted.workflows.length,1);assert.equal(persisted.executions.length,1);assert.equal(persisted.crmCustomers[0].lastRequest,'customer request details');assert.deepEqual(persisted.crmCustomers[0].attachments,['customer_request.pdf']);assert.equal(persisted.crmCustomers[0].lastWorkflowExecution,'30c43067-cb05-458c-b2b5-5b77099c0f18');assert.equal(persisted.slackMessages.length,1);assert.equal(persisted.slackMessages[0].channel,'#customer-support');assert.equal(persisted.slackMessages[0].text,'Customer request processed for ABC Technologies.')});

test('customer lookup failure stops before CRM update and Slack, then records human intervention',async t=>{const fixture=await startFixture(t,{customers:[]});const response=await fixture.request();assert.equal(response.status,409);const body=await response.json();assert.equal(body.failedStep,'crm_search');assert.equal(body.humanInterventionRequired,true);assert.match(body.error,/Customer ABC Technologies could not be found/);const persisted=JSON.parse(fs.readFileSync(fixture.store));assert.equal(persisted.executions.length,1);assert.equal(persisted.executions[0].status,'failed');assert.equal(persisted.executions[0].failedStep,'crm_search');assert.equal(persisted.executions[0].humanInterventionRequired,true);assert.deepEqual(persisted.executions[0].steps.map(step=>step.step),['gmail','download_attachment']);assert.equal(persisted.slackMessages.length,0)});

test('only active workflows can execute',async t=>{for(const status of ['discovered','needs_approval','paused','ignored','rejected']){const fixture=await startFixture(t,{status});const response=await fixture.request();assert.equal(response.status,409,status);assert.match((await response.json()).error,/Approve/,status);const persisted=JSON.parse(fs.readFileSync(fixture.store));assert.equal(persisted.executions.length,0,status);assert.equal(persisted.slackMessages.length,0,status)}});
