import express from 'express';
import fs from 'fs'; import path from 'path'; import crypto from 'crypto'; import bcrypt from 'bcryptjs'; import {z} from 'zod';
import {discover,understand} from './workflow-engine.js';
const app=express(), file=path.resolve('server/data.json'); app.use(express.json());
const id=()=>crypto.randomUUID(), now=()=>new Date().toISOString();
const actions=[['Gmail','Read customer request','API Integration'],['Files','Download PDF attachment','Application Integration'],['CRM','Update customer record','API Integration'],['Slack','Send #support notification','API Integration']];
const seed=()=>({users:[],sessions:{},observing:false,events:[
 {id:id(),time:'09:41',application:'Gmail',action:'Opened customer email',type:'Read',status:'Captured'}, {id:id(),time:'09:42',application:'Gmail',action:'Downloaded invoice.pdf',type:'File',status:'Captured'}, {id:id(),time:'09:44',application:'Chrome',action:'Opened CRM',type:'Navigation',status:'Captured'}, {id:id(),time:'09:45',application:'CRM',action:'Searched ABC Technologies',type:'Search',status:'Captured'}, {id:id(),time:'09:46',application:'CRM',action:'Updated customer record',type:'Write',status:'Captured'}, {id:id(),time:'09:47',application:'Slack',action:'Sent message to #support',type:'Communication',status:'Captured'}
],workflows:[],executions:[],integrations:['Gmail','Slack','Google Drive','CRM','Chrome','Microsoft Excel'].map(name=>({id:id(),name,status:'Simulated connected',permissions:'Demo access'}))});
let db=fs.existsSync(file)?JSON.parse(fs.readFileSync(file,'utf8')):seed(); db.crmCustomers??=[{id:'CUST-001',name:'ABC Technologies',lastRequest:null,updatedAt:null}];db.slackMessages??=[]; const save=()=>fs.writeFileSync(file,JSON.stringify(db,null,2));
const score=w=>Math.min(100,Math.round(25+20+20+15+(w.reliability||14)));
function demo(){ if(db.workflows.length) return; const mk=(name,apps,status='discovered')=>({id:id(),name,description:'AI-detected repetitive cross-application workflow',trigger:'new_customer_email',status,occurrences:9,avgDuration:684,weeklyMinutes:102,similarity:91,reliability:14,opportunityScore:94,createdAt:now(),updatedAt:now(),version:1,actions:apps.map((a,i)=>({id:id(),application:a[0],action:a[1],executionMethod:a[2]||'API Integration',order:i+1,inputs:'Customer ID, request details',approval:a[0]==='CRM'||a[0]==='Slack'})),conditions:[{if:'customer_not_found',action:'request_human_intervention'}],variables:['customerId','requestDetails'],explanation:'9 similar sequences across 4 apps with 91% similarity.'});
 db.workflows=[mk('Process Customer Request',actions),mk('Process Invoice',[['Gmail','Read invoice email'],['Google Drive','Store invoice'],['Microsoft Excel','Update invoice sheet']]),mk('Daily Report',[['Microsoft Excel','Generate summary'],['Slack','Share daily report']],'active'),mk('Candidate Processing',[['Gmail','Read candidate email'],['Files','Download resume'],['CRM','Update ATS'],['Slack','Notify hiring team']])]; save(); }
const actionMeta={open_email:['Gmail','Open customer email'],download_attachment:['Files','Download attachment'],search_customer:['CRM','Search customer'],update_customer:['CRM','Update customer record'],send_message:['Slack','Send notification']};
function workflowFromCandidate(candidate){const intelligence=understand(candidate.tokens);const signature=candidate.tokens.join('|');const actions=candidate.tokens.map((token,order)=>{const [application,action]=actionMeta[token]||['Browser',token.replaceAll('_',' ')];return{id:id(),application,action,executionMethod:application==='CRM'||application==='Slack'||application==='Gmail'?'API Integration':'Application Integration',order:order+1,inputs:'Derived from observed activity',approval:application==='CRM'||application==='Slack'}});return{id:id(),name:intelligence.workflowName,description:intelligence.description,trigger:intelligence.trigger,status:'discovered',occurrences:candidate.occurrences,avgDuration:candidate.averageDuration,weeklyMinutes:candidate.estimatedWeeklyMinutes,similarity:candidate.similarityScore,reliability:candidate.breakdown.reliability,opportunityScore:candidate.opportunityScore,scoreBreakdown:candidate.breakdown,applications:candidate.apps,discoverySignature:signature,createdAt:now(),updatedAt:now(),version:1,actions,conditions:intelligence.conditions,variables:intelligence.variables,explanation:intelligence.explanation,provider:intelligence.provider}}
function auth(req,res,next){const token=req.headers.authorization?.replace('Bearer ',''); if(!token||!db.sessions[token]) return res.status(401).json({error:'Sign in required'}); req.user=db.sessions[token];next();}
const credentials=z.object({name:z.string().max(80).optional(),email:z.string().email(),password:z.string().min(6).max(128)});
app.post('/api/auth/register',async(req,res)=>{let parsed=credentials.safeParse(req.body);if(!parsed.success)return res.status(400).json({error:'Use a valid email and a password of at least 6 characters.'});let {name,email,password}=parsed.data;if(db.users.some(u=>u.email===email))return res.status(409).json({error:'Email already registered.'});let u={id:id(),name:name||'Workflow builder',email,passwordHash:await bcrypt.hash(password,12)};db.users.push(u);let token=id();db.sessions[token]=u.id;save();res.json({token,user:{id:u.id,name:u.name,email:u.email}})});
app.post('/api/auth/login',async(req,res)=>{let parsed=credentials.pick({email:true,password:true}).safeParse(req.body);if(!parsed.success)return res.status(400).json({error:'Enter a valid email and password.'});let u=db.users.find(x=>x.email===parsed.data.email);let valid=u&&((u.passwordHash.startsWith('$2'))?await bcrypt.compare(parsed.data.password,u.passwordHash):u.passwordHash===crypto.createHash('sha256').update(parsed.data.password).digest('hex'));if(!valid)return res.status(401).json({error:'Incorrect email or password.'});if(!u.passwordHash.startsWith('$2'))u.passwordHash=await bcrypt.hash(parsed.data.password,12);let token=id();db.sessions[token]=u.id;save();res.json({token,user:{id:u.id,name:u.name,email:u.email}})});
app.post('/api/auth/logout',auth,(req,res)=>{delete db.sessions[req.headers.authorization.replace('Bearer ','')];save();res.json({ok:true})});
app.get('/api/auth/me',auth,(req,res)=>{let u=db.users.find(x=>x.id===req.user);res.json({user:u&&{id:u.id,name:u.name,email:u.email}})});
app.post('/api/demo',auth,(req,res)=>{demo();res.json({ok:true})});
app.post('/api/demo/reset',auth,(req,res)=>{const users=db.users,sessions=db.sessions;db={...seed(),users,sessions,crmCustomers:[{id:'CUST-001',name:'ABC Technologies',lastRequest:null,updatedAt:null}],slackMessages:[]};save();res.json({ok:true})});
app.get('/api/demo/state',auth,(req,res)=>res.json({crmCustomers:db.crmCustomers,slackMessages:db.slackMessages}));
app.post('/api/discover',auth,(req,res)=>{const candidates=discover(db.events).filter(candidate=>candidate.tokens.length>=3);const persisted=[];let created=0;for(const candidate of candidates){const signature=candidate.tokens.join('|');let workflow=db.workflows.find(item=>item.discoverySignature===signature);if(!workflow){workflow=workflowFromCandidate(candidate);db.workflows.unshift(workflow);created++}persisted.push(workflow)}if(created)save();res.json({provider:'local',created,candidates:persisted})});
app.get('/api/dashboard',auth,(req,res)=>{const completed=db.executions.filter(x=>x.status==='completed');const active=db.workflows.filter(w=>w.status==='active');const discovered=db.workflows.filter(w=>w.status==='discovered'||w.status==='needs_approval');const saved=completed.reduce((n,e)=>{const w=db.workflows.find(x=>x.id===e.workflowId);return n+Math.max(0,((w?.avgDuration||0)-Number(e.duration||0))/3600)},0);res.json({discovered:discovered.length,active:active.length,tasks:completed.length,time:saved.toFixed(1),candidate:discovered[0]||null})});
app.get('/api/activity',auth,(req,res)=>res.json({observing:db.observing,events:db.events}));
app.post('/api/activity/:mode',auth,(req,res)=>{db.observing=req.params.mode==='start';save();res.json({observing:db.observing})});
app.post('/api/activity/event',auth,(req,res)=>{let samples=[['Gmail','Opened customer request'],['Files','Downloaded customer-document.pdf'],['CRM','Updated customer record'],['Slack','Sent workflow notification']];let s=samples[db.events.length%samples.length];let e={id:id(),time:new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}),application:s[0],action:s[1],type:'Demo activity',status:'Captured'};db.events.unshift(e);save();res.json(e)});
app.get('/api/workflows',auth,(req,res)=>res.json(db.workflows)); app.get('/api/workflows/:id',auth,(req,res)=>{let w=db.workflows.find(x=>x.id===req.params.id);w?res.json(w):res.status(404).json({error:'Workflow not found'})});
app.post('/api/workflows',auth,(req,res)=>{let q=(req.body.prompt||'').toLowerCase();let w={id:id(),name:q.includes('invoice')?'Process Invoice':q.includes('report')?'Daily Report':'Process Customer Request',description:'Generated from your request using the local deterministic parser.',trigger:'new_customer_email',status:'needs_approval',occurrences:1,avgDuration:684,weeklyMinutes:102,similarity:88,reliability:14,opportunityScore:94,createdAt:now(),updatedAt:now(),version:1,actions:actions.map((a,i)=>({id:id(),application:a[0],action:a[1],executionMethod:a[2],order:i+1,inputs:'Customer ID, request details',approval:i>1})),conditions:[{if:'customer_not_found',action:'request_human_intervention'}],variables:['customerId']};db.workflows.unshift(w);save();res.json(w)});
app.put('/api/workflows/:id',auth,(req,res)=>{let w=db.workflows.find(x=>x.id===req.params.id);if(!w)return res.status(404).json({error:'Workflow not found'});Object.assign(w,req.body,{updatedAt:now()});save();res.json(w)});
app.delete('/api/workflows/:id',auth,(req,res)=>{db.workflows=db.workflows.filter(x=>x.id!==req.params.id);save();res.json({ok:true})});
app.post('/api/workflows/:id/:action',auth,(req,res)=>{let w=db.workflows.find(x=>x.id===req.params.id);if(!w)return res.status(404).json({error:'Workflow not found'});let a=req.params.action;if(a==='approve'||a==='resume')w.status='active';if(a==='reject')w.status='rejected';if(a==='pause')w.status='paused';if(a==='ignore')w.status='ignored';if(a==='simulate')return res.json({steps:w.actions.map(x=>`Prepared: ${x.action}`),duration:'2.8 seconds',externalActions:false});if(a==='run'){if(w.status!=='active')return res.status(409).json({error:'Approve this workflow before running it.'});let customer=db.crmCustomers.find(x=>x.name==='ABC Technologies');if(!customer){let e={id:id(),workflowId:w.id,status:'needs_human_intervention',startedAt:now(),completedAt:now(),duration:0,error:'Customer could not be identified.',steps:[]};db.executions.unshift(e);save();return res.status(409).json({error:e.error,execution:e})}customer.lastRequest='Customer request attachment processed';customer.updatedAt=now();db.slackMessages.unshift({id:id(),channel:'#support',text:'Customer request processed for ABC Technologies',createdAt:now(),workflowId:w.id});let e={id:id(),workflowId:w.id,status:'completed',startedAt:now(),completedAt:now(),duration:18.4,steps:w.actions.map(x=>({...x,status:'success'}))};db.executions.unshift(e);save();return res.json(e)} save();res.json(w)});
app.get('/api/executions',auth,(req,res)=>res.json(db.executions));
app.get('/api/analytics',auth,(req,res)=>{const e=db.executions,completed=e.filter(x=>x.status==='completed'),failed=e.filter(x=>x.status==='failed'),human=e.filter(x=>x.status==='needs_human_intervention'),saved=completed.reduce((n,x)=>{const w=db.workflows.find(y=>y.id===x.workflowId);return n+Math.max(0,((w?.avgDuration||0)-Number(x.duration||0))/3600)},0);const today=['Mon','Tue','Wed','Thu','Fri','Sat','Sun'];const todayIndex=(new Date().getDay()+6)%7;res.json({completed:completed.length,failed:failed.length,human:human.length,timeSaved:+saved.toFixed(1),series:today.map((day,i)=>({day,runs:i===todayIndex?e.length:0,hours:i===todayIndex?+saved.toFixed(1):0})),repetitive:db.workflows.slice(0,5).map(w=>w.name)})});
app.get('/api/integrations',auth,(req,res)=>res.json(db.integrations)); app.post('/api/integrations/:id/:action',auth,(req,res)=>{let x=db.integrations.find(i=>i.id===req.params.id);if(!x)return res.status(404).json({error:'Integration not found'});x.status=req.params.action==='connect'?'Simulated connected':'Disconnected';save();res.json(x)});
app.post('/api/emergency-stop',auth,(req,res)=>{db.workflows.forEach(w=>{if(w.status==='active')w.status='paused'});save();res.json({ok:true})});
app.post('/api/safety/emergency-stop',auth,(req,res)=>{db.workflows.forEach(w=>{if(w.status==='active')w.status='paused'});save();res.json({ok:true})});
app.listen(3001,()=>console.log('WorkFlowOS API on http://localhost:3001'));
