import express from 'express';
import fs from 'fs'; import path from 'path'; import crypto from 'crypto'; import bcrypt from 'bcryptjs'; import {z} from 'zod';
import {discover} from './workflow-engine.js';
import {understandWorkflow} from './workflow-understanding.js';
const app=express(), file=path.resolve(process.env.WORKFLOWOS_DATA_FILE||'server/data.json'); app.use(express.json());
app.use((req,res,next)=>{res.setHeader('Access-Control-Allow-Origin','*');res.setHeader('Access-Control-Allow-Methods','GET,POST,PUT,DELETE,OPTIONS');res.setHeader('Access-Control-Allow-Headers','Content-Type,Authorization');if(req.method==='OPTIONS')return res.sendStatus(204);next()});
const id=()=>crypto.randomUUID(), now=()=>new Date().toISOString();
const actions=[['Gmail','Read customer request','API Integration'],['Files','Download PDF attachment','Application Integration'],['CRM','Update customer record','API Integration'],['Slack','Send #support notification','API Integration']];
const seed=()=>({users:[],sessions:{},observing:false,events:[
 {id:id(),time:'09:41',application:'Gmail',action:'Opened customer email',type:'Read',status:'Captured'}, {id:id(),time:'09:42',application:'Gmail',action:'Downloaded invoice.pdf',type:'File',status:'Captured'}, {id:id(),time:'09:44',application:'Chrome',action:'Opened CRM',type:'Navigation',status:'Captured'}, {id:id(),time:'09:45',application:'CRM',action:'Searched ABC Technologies',type:'Search',status:'Captured'}, {id:id(),time:'09:46',application:'CRM',action:'Updated customer record',type:'Write',status:'Captured'}, {id:id(),time:'09:47',application:'Slack',action:'Sent message to #support',type:'Communication',status:'Captured'}
],workflows:[],executions:[],integrations:['Gmail','Slack','Google Drive','CRM','Chrome','Microsoft Excel'].map(name=>({id:id(),name,status:'Simulated connected',permissions:'Demo access'}))});
let db=fs.existsSync(file)?JSON.parse(fs.readFileSync(file,'utf8')):seed(); db.crmCustomers??=[{id:'CUST-001',name:'ABC Technologies',lastRequest:null,updatedAt:null}];db.slackMessages??=[]; let migrated=false;for(const workflow of db.workflows){if(!workflow.source){workflow.source=workflow.discoverySignature?'activity-discovery':'seeded-demo';migrated=true}const legacyTokens=workflow.discoverySignature?.split('|')||[];if(workflow.source==='activity-discovery'&&!workflow.legacyContaminated&&(legacyTokens.length>12||legacyTokens.includes('opened_page'))){workflow.legacyContaminated=true;workflow.status='ignored';migrated=true}} const save=()=>fs.writeFileSync(file,JSON.stringify(db,null,2));if(migrated)save();
const score=w=>Math.min(100,Math.round(25+20+20+15+(w.reliability||14)));
function demo(){ if(db.workflows.length) return; const mk=(name,apps,status='discovered')=>({id:id(),name,description:'AI-detected repetitive cross-application workflow',trigger:'new_customer_email',status,source:'seeded-demo',occurrences:9,avgDuration:684,weeklyMinutes:102,similarity:91,reliability:14,opportunityScore:94,createdAt:now(),updatedAt:now(),version:1,actions:apps.map((a,i)=>({id:id(),application:a[0],action:a[1],executionMethod:a[2]||'API Integration',order:i+1,inputs:'Customer ID, request details',approval:a[0]==='CRM'||a[0]==='Slack'})),conditions:[{if:'customer_not_found',action:'request_human_intervention'}],variables:['customerId','requestDetails'],explanation:'9 similar sequences across 4 apps with 91% similarity.'});
 db.workflows=[mk('Process Customer Request',actions),mk('Process Invoice',[['Gmail','Read invoice email'],['Google Drive','Store invoice'],['Microsoft Excel','Update invoice sheet']]),mk('Daily Report',[['Microsoft Excel','Generate summary'],['Slack','Share daily report']],'active'),mk('Candidate Processing',[['Gmail','Read candidate email'],['Files','Download resume'],['CRM','Update ATS'],['Slack','Notify hiring team']])]; save(); }
const actionMeta={open_email:['Gmail','Open customer email'],download_attachment:['Files','Download attachment'],search_customer:['CRM','Search customer'],update_customer:['CRM','Update customer record'],send_message:['Slack','Send notification']};
async function workflowFromCandidate(candidate){const intelligence=await understandWorkflow(candidate.tokens);const signature=candidate.tokens.join('|');const actions=candidate.tokens.map((token,order)=>{const [application,action]=actionMeta[token]||['Browser',token.replaceAll('_',' ')];return{id:id(),application,action,executionMethod:application==='CRM'||application==='Slack'||application==='Gmail'?'API Integration':'Application Integration',order:order+1,inputs:'Derived from observed activity',approval:application==='CRM'||application==='Slack'}});return{id:id(),name:intelligence.workflowName,description:intelligence.description,trigger:intelligence.trigger,status:'discovered',source:'activity-discovery',occurrences:candidate.occurrences,avgDuration:candidate.averageDuration,weeklyMinutes:candidate.estimatedWeeklyMinutes,similarity:candidate.similarityScore,reliability:candidate.breakdown.reliability,opportunityScore:candidate.opportunityScore,scoreBreakdown:candidate.breakdown,applications:candidate.apps,discoverySignature:signature,createdAt:now(),updatedAt:now(),version:1,actions,conditions:intelligence.conditions,variables:intelligence.variables,explanation:intelligence.explanation,provider:intelligence.provider,understandingSource:intelligence.understandingSource}}
function auth(req,res,next){const token=req.headers.authorization?.replace('Bearer ',''); if(!token||!db.sessions[token]) return res.status(401).json({error:'Sign in required'}); req.user=db.sessions[token];next();}
const credentials=z.object({name:z.string().max(80).optional(),email:z.string().email(),password:z.string().min(6).max(128)});
app.post('/api/auth/register',async(req,res)=>{let parsed=credentials.safeParse(req.body);if(!parsed.success)return res.status(400).json({error:'Use a valid email and a password of at least 6 characters.'});let {name,email,password}=parsed.data;if(db.users.some(u=>u.email===email))return res.status(409).json({error:'Email already registered.'});let u={id:id(),name:name||'Workflow builder',email,passwordHash:await bcrypt.hash(password,12)};db.users.push(u);let token=id();db.sessions[token]=u.id;save();res.json({token,user:{id:u.id,name:u.name,email:u.email}})});
app.post('/api/auth/login',async(req,res)=>{let parsed=credentials.pick({email:true,password:true}).safeParse(req.body);if(!parsed.success)return res.status(400).json({error:'Enter a valid email and password.'});let u=db.users.find(x=>x.email===parsed.data.email);let valid=u&&((u.passwordHash.startsWith('$2'))?await bcrypt.compare(parsed.data.password,u.passwordHash):u.passwordHash===crypto.createHash('sha256').update(parsed.data.password).digest('hex'));if(!valid)return res.status(401).json({error:'Incorrect email or password.'});if(!u.passwordHash.startsWith('$2'))u.passwordHash=await bcrypt.hash(parsed.data.password,12);let token=id();db.sessions[token]=u.id;save();res.json({token,user:{id:u.id,name:u.name,email:u.email}})});
app.post('/api/auth/logout',auth,(req,res)=>{delete db.sessions[req.headers.authorization.replace('Bearer ','')];save();res.json({ok:true})});
app.get('/api/auth/me',auth,(req,res)=>{let u=db.users.find(x=>x.id===req.user);res.json({user:u&&{id:u.id,name:u.name,email:u.email}})});
app.post('/api/demo',auth,(req,res)=>{demo();res.json({ok:true})});
app.post('/api/demo/reset',auth,(req,res)=>{const users=db.users,sessions=db.sessions;db={...seed(),users,sessions,crmCustomers:[{id:'CUST-001',name:'ABC Technologies',lastRequest:null,updatedAt:null}],slackMessages:[]};save();res.json({ok:true})});
app.get('/api/demo/state',auth,(req,res)=>res.json({crmCustomers:db.crmCustomers,slackMessages:db.slackMessages}));
app.post('/api/demo/customer-request-sequence',auth,(req,res)=>{const sessionId=`demo-customer-request-${id()}`,base=Date.now();const steps=[['Gmail','Opened customer request','OPEN_EMAIL',{customer:'ABC Technologies'}],['Files','Downloaded customer_request.pdf','DOWNLOAD_FILE',{customer:'ABC Technologies'}],['CRM','Searched for ABC Technologies','CRM_SEARCH',{customer:'ABC Technologies'}],['CRM','Updated customer record','CRM_UPDATE',{customer:'ABC Technologies',request:'customer request details',attachment:'customer_request.pdf'}],['Slack','Sent notification to #customer-support','SLACK_MESSAGE',{customer:'ABC Technologies'}]];const events=steps.map(([application,action,type,metadata],index)=>{const timestamp=new Date(base+index*1000).toISOString();return{id:id(),time:new Date(timestamp).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}),timestamp,userId:req.user,sessionId,application,action,description:action,type,status:'Captured',source:'demo',metadata,duration:4}});db.events.push(...events);save();res.status(201).json({success:true,message:'Customer request sequence recorded.',eventsAdded:events.length,events,sessionId})});
app.post('/api/discover',auth,async(req,res)=>{const candidates=discover(db.events).filter(candidate=>candidate.tokens.length>=3);const persisted=[];let created=0;const existingActivitySignatures=new Set(db.workflows.filter(item=>item.source==='activity-discovery'&&!item.legacyContaminated&&!item.ignored&&item.status!=='ignored').map(item=>item.discoverySignature).filter(Boolean));const seededSignatures=db.workflows.filter(item=>item.source==='seeded-demo'&&item.discoverySignature).length;for(const candidate of candidates){const signature=candidate.tokens.join('|');let workflow=db.workflows.find(item=>item.source==='activity-discovery'&&!item.legacyContaminated&&!item.ignored&&item.status!=='ignored'&&item.discoverySignature===signature);const wasCreated=!workflow;if(wasCreated){workflow=await workflowFromCandidate(candidate);db.workflows.unshift(workflow);existingActivitySignatures.add(signature);created++}persisted.push(workflow);console.info('[discovery] candidate', {signature,created:wasCreated,existingActivitySignatures:existingActivitySignatures.size,seededSignaturesIgnored:seededSignatures})}if(created)save();console.info('[discovery] completed', {extractedWindows:candidates.length,created,existingActivitySignatures:existingActivitySignatures.size,seededSignaturesIgnored:seededSignatures});res.json({provider:created?persisted[0]?.provider:'local',created,candidates:persisted})});
app.get('/api/dashboard',auth,(req,res)=>{const completed=db.executions.filter(x=>x.status==='completed');const active=db.workflows.filter(w=>w.status==='active'&&!w.legacyContaminated&&w.status!=='ignored');const discovered=db.workflows.filter(w=>(w.status==='discovered'||w.status==='needs_approval')&&!w.legacyContaminated&&w.status!=='ignored');const saved=completed.reduce((n,e)=>{const w=db.workflows.find(x=>x.id===e.workflowId);return n+Math.max(0,((w?.avgDuration||0)-Number(e.duration||0))/3600)},0);res.json({discovered:discovered.length,active:active.length,tasks:completed.length,time:saved.toFixed(1),candidate:discovered[0]||null})});
app.get('/api/activity',auth,(req,res)=>res.json({observing:db.observing,events:db.events}));
app.post('/api/activity/start',auth,(req,res)=>{db.observing=true;save();res.json({observing:db.observing})});
app.post('/api/activity/stop',auth,(req,res)=>{db.observing=false;save();res.json({observing:db.observing})});
const extensionEvent=z.object({eventType:z.enum(['PAGE_OPEN','SEARCH','FORM_SUBMIT','DOWNLOAD_FILE','OPEN_EMAIL']),timestamp:z.string().datetime().optional(),domain:z.string().max(255).optional(),pageTitle:z.string().max(200).optional(),description:z.string().max(300).optional(),source:z.literal('chrome-extension')});
app.post('/api/activity/event',(req,res)=>{const incoming=extensionEvent.safeParse(req.body);let e;if(incoming.success){const event=incoming.data;const labels={PAGE_OPEN:'Opened page',SEARCH:'Performed search',FORM_SUBMIT:'Submitted form',DOWNLOAD_FILE:'Downloaded file',OPEN_EMAIL:'Opened email'};console.info('[activity] Chrome extension event received', {eventType:event.eventType,domain:event.domain||null,source:event.source});e={id:id(),time:new Date(event.timestamp||Date.now()).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}),timestamp:event.timestamp||now(),application:event.domain||'Chrome',action:event.description||labels[event.eventType],type:event.eventType,status:'Captured',source:event.source,metadata:{domain:event.domain||null,pageTitle:event.pageTitle||null}}}else if(req.headers.authorization){let samples=[['Gmail','Opened customer request'],['Files','Downloaded customer-document.pdf'],['CRM','Updated customer record'],['Slack','Sent workflow notification']];let s=samples[db.events.length%samples.length];e={id:id(),time:new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}),application:s[0],action:s[1],type:'Demo activity',status:'Captured',source:'demo'} }else {console.warn('[activity] rejected unsupported event', {source:req.body?.source||null,eventType:req.body?.eventType||null});return res.status(400).json({error:'Send a supported semantic Chrome extension event.'})}db.events.unshift(e);save();console.info('[activity] event persisted', {id:e.id,source:e.source||'demo',totalEvents:db.events.length});res.status(201).json(e)});
app.get('/api/workflows',auth,(req,res)=>{const visible=db.workflows.filter(w=>!(w.source==='activity-discovery'&&(w.status==='ignored'||w.legacyContaminated||w.ignored)));res.json(visible);}); app.get('/api/workflows/:id',auth,(req,res)=>{let w=db.workflows.find(x=>x.id===req.params.id);w?res.json(w):res.status(404).json({error:'Workflow not found'})});
app.post('/api/workflows',auth,(req,res)=>{let q=(req.body.prompt||'').toLowerCase();let w={id:id(),name:q.includes('invoice')?'Process Invoice':q.includes('report')?'Daily Report':'Process Customer Request',description:'Generated from your request using the local deterministic parser.',trigger:'new_customer_email',status:'needs_approval',occurrences:1,avgDuration:684,weeklyMinutes:102,similarity:88,reliability:14,opportunityScore:94,createdAt:now(),updatedAt:now(),version:1,actions:actions.map((a,i)=>({id:id(),application:a[0],action:a[1],executionMethod:a[2],order:i+1,inputs:'Customer ID, request details',approval:i>1})),conditions:[{if:'customer_not_found',action:'request_human_intervention'}],variables:['customerId']};db.workflows.unshift(w);save();res.json(w)});
app.put('/api/workflows/:id',auth,(req,res)=>{let w=db.workflows.find(x=>x.id===req.params.id);if(!w)return res.status(404).json({error:'Workflow not found'});Object.assign(w,req.body,{updatedAt:now()});save();res.json(w)});
app.delete('/api/workflows/:id',auth,(req,res)=>{db.workflows=db.workflows.filter(x=>x.id!==req.params.id);save();res.json({ok:true})});
const localCustomerRequest=()=>{const event=[...db.events].reverse().find(item=>item.metadata?.customer==='ABC Technologies'&&/customer request/i.test(item.action||''));return{customer:event?.metadata?.customer||'ABC Technologies',attachment:event?.metadata?.attachment||'customer_request.pdf',request:event?.metadata?.request||'customer request details'}};
const completedStep=(step,application,result)=>({step,application,status:'completed',result});
function runCustomerRequestWorkflow(workflow){const startedAt=now(),request=localCustomerRequest(),steps=[];steps.push(completedStep('gmail','Gmail',{customer:request.customer,request:request.request}));steps.push(completedStep('download_attachment','Files',{attachment:request.attachment}));const customer=db.crmCustomers.find(item=>item.name===request.customer);if(!customer){const execution={id:id(),workflowId:workflow.id,workflowName:workflow.name,status:'failed',startedAt,completedAt:now(),duration:0,steps,failedStep:'crm_search',humanInterventionRequired:true,error:`Customer ${request.customer} could not be found.`,result:'Customer lookup failed before any CRM update or Slack notification.'};db.executions.unshift(execution);save();return{ok:false,execution}}steps.push(completedStep('crm_search','CRM',{customerId:customer.id,customer:customer.name}));customer.lastRequest=request.request;customer.attachments=[...(customer.attachments||[]),request.attachment];customer.lastWorkflowExecution=workflow.id;customer.updatedAt=now();steps.push(completedStep('crm_update','CRM',{customerId:customer.id,updatedFields:['lastRequest','attachments','lastWorkflowExecution']}));const message={id:id(),channel:'#customer-support',text:`Customer request processed for ${customer.name}.`,createdAt:now(),workflowId:workflow.id,customerId:customer.id,attachment:request.attachment};db.slackMessages.unshift(message);steps.push(completedStep('slack_notification','Slack',{channel:message.channel,messageId:message.id}));const completedAt=now(),execution={id:id(),workflowId:workflow.id,workflowName:workflow.name,status:'completed',startedAt,completedAt,duration:Math.max(0.001,(Date.parse(completedAt)-Date.parse(startedAt))/1000),steps,failedStep:null,humanInterventionRequired:false,result:{customerId:customer.id,crmUpdated:true,slackMessageId:message.id}};db.executions.unshift(execution);save();return{ok:true,execution}}
app.post('/api/workflows/:id/:action',auth,(req,res)=>{let w=db.workflows.find(x=>x.id===req.params.id);if(!w)return res.status(404).json({error:'Workflow not found'});let a=req.params.action;if(a==='approve'){if(!['discovered','needs_approval'].includes(w.status))return res.status(409).json({error:'Only a discovered workflow can be approved.'});w.status='active'}if(a==='resume'){if(w.status!=='paused')return res.status(409).json({error:'Only a paused workflow can be resumed.'});w.status='active'}if(a==='reject'){if(!['discovered','needs_approval'].includes(w.status))return res.status(409).json({error:'Only a discovered workflow can be rejected.'});w.status='rejected'}if(a==='pause')w.status='paused';if(a==='ignore')w.status='ignored';if(a==='simulate')return res.json({steps:w.actions.map(x=>`Prepared: ${x.action}`),duration:'2.8 seconds',externalActions:false});if(a==='run'){if(w.status!=='active')return res.status(409).json({error:'Approve this workflow before running it.'});const outcome=runCustomerRequestWorkflow(w);if(!outcome.ok)return res.status(409).json({error:outcome.execution.error,failedStep:outcome.execution.failedStep,humanInterventionRequired:true,execution:outcome.execution});return res.json(outcome.execution)}save();res.json(w)});
app.get('/api/executions',auth,(req,res)=>res.json(db.executions));
app.get('/api/analytics',auth,(req,res)=>{const e=db.executions,completed=e.filter(x=>x.status==='completed'),failed=e.filter(x=>x.status==='failed'),human=e.filter(x=>x.status==='needs_human_intervention'||x.humanInterventionRequired),saved=completed.reduce((n,x)=>{const w=db.workflows.find(y=>y.id===x.workflowId);return n+Math.max(0,((w?.avgDuration||0)-Number(x.duration||0))/3600)},0);const today=['Mon','Tue','Wed','Thu','Fri','Sat','Sun'];const todayIndex=(new Date().getDay()+6)%7;res.json({completed:completed.length,failed:failed.length,human:human.length,timeSaved:+saved.toFixed(1),series:today.map((day,i)=>({day,runs:i===todayIndex?e.length:0,hours:i===todayIndex?+saved.toFixed(1):0})),repetitive:db.workflows.slice(0,5).map(w=>w.name)})});
app.get('/api/integrations',auth,(req,res)=>res.json(db.integrations)); app.post('/api/integrations/:id/:action',auth,(req,res)=>{let x=db.integrations.find(i=>i.id===req.params.id);if(!x)return res.status(404).json({error:'Integration not found'});x.status=req.params.action==='connect'?'Simulated connected':'Disconnected';save();res.json(x)});
app.post('/api/emergency-stop',auth,(req,res)=>{db.workflows.forEach(w=>{if(w.status==='active')w.status='paused'});save();res.json({ok:true})});
app.post('/api/safety/emergency-stop',auth,(req,res)=>{db.workflows.forEach(w=>{if(w.status==='active')w.status='paused'});save();res.json({ok:true})});
app.use('/api',(req,res)=>res.status(404).json({error:`Unknown API endpoint: ${req.method} ${req.originalUrl}`}));
const port=Number(process.env.PORT||3001);
const httpServer=app.listen(port,()=>{httpServer.ref();console.log(`WorkFlowOS API on http://localhost:${port}`)});
httpServer.on('error',error=>{console.error(`WorkFlowOS API failed to listen on port ${port}: ${error.message}`);process.exitCode=1});
